version: "3.9"

services:

  db:
    image: postgres:16-alpine

    container_name: inventory_db

    restart: always

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: inventory_backend

    restart: always

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventory_db

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  postgres_data: